#!/usr/bin/env python3
"""Extract translations for the desktop action name from .po files.

Scans po/*.po for the msgid "Remove this AppImage" (without msgctxt)
and generates a C++ header with a static array of {locale, translation}
pairs. The integration code writes these as Name[locale]=translation
entries in the .desktop file so KConfig can pick the right language at
display time.

Usage:
    python3 extract-action-translations.py <po-dir> <output-header>
"""
import os
import re
import sys


def unescape_po(s):
    """Unescape a gettext .po string."""
    s = s.replace('\\n', '\n')
    s = s.replace('\\t', '\t')
    s = s.replace('\\"', '"')
    s = s.replace('\\\\', '\\')
    return s


def parse_inline_string(line):
    """Extract the quoted string from a line like: msgid "text"
    Returns the unescaped content, or None if no quoted string found.
    """
    m = re.search(r'"((?:[^"\\]|\\.)*)"', line)
    if m:
        return unescape_po(m.group(1))
    return None


def parse_continuation(lines, start):
    """Parse multi-line continuation strings (lines starting with ").
    Returns (concatenated_string, next_index).
    """
    parts = []
    i = start
    while i < len(lines):
        line = lines[i].strip()
        if line.startswith('"'):
            m = re.search(r'"((?:[^"\\]|\\.)*)"', line)
            if m:
                parts.append(unescape_po(m.group(1)))
            i += 1
        else:
            break
    return ''.join(parts), i


def extract_msgstr(po_path, target_msgid):
    """Extract msgstr for the given msgid that has NO msgctxt.

    Returns the translation string, or None if not found.
    """
    with open(po_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    i = 0
    while i < len(lines):
        line = lines[i].strip()

        # Skip entries with msgctxt — we want the entry without context
        if line.startswith('msgctxt'):
            i += 1
            # Skip to the next blank line or non-continuation line
            while i < len(lines):
                inner = lines[i].strip()
                if inner.startswith('msgid') or inner.startswith('msgstr'):
                    # Skip the inline string + any continuations
                    i += 1
                    while i < len(lines) and lines[i].strip().startswith('"'):
                        i += 1
                elif inner == '' or not inner.startswith('"'):
                    break
                i += 1
            continue

        if line.startswith('msgid '):
            msgid_text = parse_inline_string(line)
            i += 1
            # Handle multi-line msgid
            if i < len(lines) and lines[i].strip().startswith('"'):
                cont, i = parse_continuation(lines, i)
                msgid_text = (msgid_text or '') + cont

            if msgid_text == target_msgid:
                # Look for msgstr
                while i < len(lines):
                    inner = lines[i].strip()
                    if inner.startswith('msgstr'):
                        msgstr_text = parse_inline_string(inner) or ''
                        i += 1
                        # Handle multi-line msgstr
                        if i < len(lines) and lines[i].strip().startswith('"'):
                            cont, i = parse_continuation(lines, i)
                            msgstr_text += cont
                        if msgstr_text:
                            return msgstr_text
                        break
                    i += 1
            continue

        i += 1

    return None


def escape_cpp(s):
    """Escape a string for use as a C++ string literal."""
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <po-dir> <output-header>", file=sys.stderr)
        sys.exit(1)

    po_dir = sys.argv[1]
    output = sys.argv[2]
    target_msgid = "Remove this AppImage"

    translations = []
    for name in sorted(os.listdir(po_dir)):
        if not name.endswith('.po'):
            continue
        lang = name[:-3]  # strip .po
        po_path = os.path.join(po_dir, name)
        translated = extract_msgstr(po_path, target_msgid)
        if translated:
            translations.append((lang, translated))

    os.makedirs(os.path.dirname(output) or '.', exist_ok=True)
    with open(output, 'w', encoding='utf-8') as f:
        f.write('// Auto-generated by cmake/extract-action-translations.py\n')
        f.write('// Do not edit manually.\n')
        f.write('#pragma once\n\n')
        f.write('namespace miryu {\n\n')
        f.write('struct ActionTranslation {\n')
        f.write('    const char* locale;\n')
        f.write('    const char* text;\n')
        f.write('};\n\n')
        f.write(f'static constexpr int actionTranslationCount = {len(translations)};\n\n')
        f.write('static const ActionTranslation actionTranslations[] = {\n')
        for lang, text in translations:
            f.write(f'    {{"{lang}", "{escape_cpp(text)}"}},\n')
        f.write('};\n\n')
        f.write('} // namespace miryu\n')

    print(f"Generated {output} with {len(translations)} translations")
    for lang, text in translations:
        print(f"  {lang}: {text}")


if __name__ == '__main__':
    main()
